version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: greenBayDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fenyo
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./Backend
      dockerfile: /Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=greenBayDB;Username=postgres;Password=fenyo
    depends_on:
      - database

# Uncomment this when frontend is finished
#  frontend:
#    build:
#      context: ./path_to_frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"

volumes:
  pgdata:
