name: Backend CD to Railway

on:
    push:
      branches: ["master"]
    workflow_dispatch:
  
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Build and Publish
        run: dotnet build Backend --configuration Release
             dotnet publish Backend -c Release -o ./output

      - name: Deploy to Railway
        uses: railwayapp/github-action@v1
        with:
          apiKey: ${{ secrets.RAILWAY_API_KEY }}
          projectId: 10fd2921-919e-4bac-8362-ae8b6c1ef6f6
          environment: production
          dir: ./output