name: Backend CD to Railway

on:
    push:
      branches: ["master"]
    workflow_dispatch:
  
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build and Publish
        run: |
            dotnet build Backend --configuration Release
            dotnet publish Backend -c Release -o ./output
        

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Login to Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}

      - name: Deploy backend to Railway
        run: railway up --dir ./output