name: Backend Deployment

on:
  push:
    paths:
      - 'Backend/**'
    branches:
      - master

defaults:
  run:
    working-directory: Backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build and Publish
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o ./output

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: YOUR_APP_NAME
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./output
