name: Backend CD to Railway

on:
  push:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    working-directory: Backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build and Publish
        run: |
            dotnet build --configuration Release
            dotnet publish -c Release -o ./output
        
      - name: Install Railway CLI
        run: npm install -g railway/cli

      - name: Login to Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}

      - name: Deploy backend to Railway
        run: railway up --dir ./output
