name: Frontend CI

on:
  push:
    paths:
      - 'Frontend/**'
    branches:
      - master
  pull_request:
    paths:
      - 'Frontend/**'
    branches:
      - master

defaults:
  run:
    working-directory: Frontend

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Change directory to Frontend
      run: cd Frontend

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
