name: Continous Deployment - Frontend - Production

on:
  push:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./Frontend

jobs:
  CI:
    name: Test and build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build

  build-and-deploy:
    name: Deploy
    needs: CI

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install railway cli
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up -s frontend -e production -d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
          RAILWAY_DOCKERFILE_PATH: Dockerfile.production
